name: Coverage

on: ["push", "pull_request"]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Generate coverage
        run: go test -coverprofile=coverage.cov -covermode=atomic ./...
      - name: Upload coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.cov
